// action types
export const FETCH_PRODUCTS_PENDING = 'FETCH_PRODUCTS_PENDING';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
export const GET_SLIDE_TO_SHOW = 'GET_SLIDE_TO_SHOW';
export const GET_POSTER_INFO = 'GET_POSTER_INFO';
export const GET_USER_INFO = 'GET_USER_INFO';
export const UPDATE_USER_LIST = 'UPDATE_USER_LIST';
export const UPDATE_LIST_MEDIA = 'UPDATE_LIST_MEDIA';
